var navs = [{
    "title": "基本",
    "icon": "fa-cubes",
    "spread": true,
    "children": [{
        "title": "Ajax",
        "icon": "&#xe641;",
        "href": "../teach/1_1_ajax/index.html"
    }, {
        "title": "IE",
        "icon": "&#xe63c;",
        "href": "../teach/1_2_IE/index.html"
    }, {
        "title": "HTTP",
        "icon": "&#xe63c;",
        "href": "../teach/1_3_HTTP/index.html"
    }, {
        "title": "CSS",
        "icon": "&#xe609;",
        "href": "../teach/1_4_CSS/index.html"
    }, {
        "title": "HTML",
        "icon": "&#xe60c;",
        "href": "../teach/1_5_HTML/index.html"
    }, {
        "title": "JS",
        "icon": "&#xe60c;",
        "href": "../teach/1_6_JS/index.html"
    }, {
        "title": "Spring配置",
        "icon": "&#xe60c;",
        "href": "../teach/1_7_Spring/spring.xml",
        "openType":"_blank"
    }, {
        "title": "Jquery",
        "icon": "&#xe60c;",
        "href": "../teach/1_8_Jquery/index.html"
    }, {
        "title": "SQL",
        "icon": "&#xe60c;",
        "href": "../teach/1_9_SQL/index.html"
    }, {
        "title": "Json",
        "icon": "&#xe60c;",
        "href": "../teach/1_10_JSObject/index.html"
    }]
}, {
    "title": "高级(参看jsp代码)",
    "icon": "fa-cogs",
    "spread": false,
    "children": [{
        "title": "DB",
        "icon": "fa-table",
        "href": "../teach/2_1_db/data/data.jsp"
    }, {
        "title": "json",
        "icon": "fa-table",
        "href": "../teach/2_2_json/data/index.jsp"
    }, {
        "title": "datatable",
        "icon": "fa-table",
        "href": "../teach/2_3_datatable/data/index.jsp"
    }, {
        "title": "stringutil",
        "icon": "fa-table",
        "href": "../teach/2_4_stringutil/data/index.jsp"
    }, {
        "title": "valid",
        "icon": "fa-table",
        "href": "../teach/2_5_valid/data/index.jsp"
    }, {
        "title": "freemark",
        "icon": "fa-table",
        "href": "../teach/2_6_freemark/index.jsp"
    }, {
        "title": "excel",
        "icon": "fa-table",
        "href": "../teach/2_12_excel/data/index.jsp"
    }, {
        "title": "DynamicRest",
        "icon": "fa-table",
        "href": "../DynamicRest/index.html"
    }]
}];